version: "3.9"
services:
    db:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        env_file:
            - ./backend/.env
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    backend:
        build: ./backend
        container_name: backend
        ports:
            - 4200:4200
        depends_on:
            - db
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules

    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        container_name: frontend
        volumes:
            - ./frontend:/src/app
            - ./frontend/node_modules
            - ./frontend/.next

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin4
        ports:
            - '5050:80'
        depends_on:
            - db

volumes:
    postgres:
